### ISSUE TITLE
Requires itself

### ISSUE THREAD

**Issue by ZanderBrown** [rilian-la-te/simple-panel#2]
i know this is replced by vala-panel which i was interested in but cmake wouldnt work anyway trying to compile generates

```
libtool: link: cannot find the library `/usr/local/lib/simple-panel/plugins/../libsimplepanel.la' or unhandled argument `/usr/local/lib/simple-panel/plugins/../libsimplepanel.la'
```

basically meaning that until i run `make install` i cannot `make` anything to `make install`

Either i'm doing something stupid or your automake is fundimentally flawed

**Comment by rilian-la-te** [comment]
This project is abandoned and superseded by vala-panel.

**Comment by rilian-la-te** [comment]
Anyway, automake version may not work, if you like, you can take cmake version from branch
