### ISSUE TITLE
A bug from vala-panel-extras-volumes

### ISSUE THREAD

**Issue by ghostplant** [rilian-la-te/simple-panel#3]
I cannot create issues in repo `vala-panel-extras` so put the reports here.

The problem of `vala-panel-extras-volumes` is when I click the volumes-task-icon that can pop up the volumes menus, then I click the first menu item which is a bar used to scale the system volume, the whole vala-panel will hang if I don't click the position accurately.

For example, if I click the very left position of the volume bar (even left than the sound symbol), then I click the normal area of vala-panel.
The vala-panel will be out of response.

**Comment by rilian-la-te** [comment]
@ghostplant please, create a bug and add a video in https://gitlab.com/vala-panel-project/vala-panel-extras
